version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    # Core linters (from default set)
    - errcheck      # Check for unchecked errors
    - govet         # Go vet checks
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Static analysis (includes gosimple)
    - unused        # Find unused code

    # Additional useful linters
    - misspell      # Find spelling mistakes
    - bodyclose     # Check HTTP response body is closed
    - durationcheck # Check for duration multiplication issues
    - errname       # Check error naming conventions
    - errorlint     # Check error wrapping
    - copyloopvar   # Check loop variable copying (Go 1.22+)
    - nilerr        # Find returning nil with non-nil error
    - wastedassign  # Find wasted assignments

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/mcoot/crosswordgame-go2

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too noisy for little benefit

  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 3

  exclude-rules:
    # Test files can have longer functions and more complexity
    - path: _test\.go
      linters:
        - errcheck
        - bodyclose

    # Allow unused parameters in interface implementations
    - linters:
        - unused
      text: "unused-parameter"
