version: '3'

vars:
  GOLANGCI_LINT: go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint
  TEMPL: go run github.com/a-h/templ/cmd/templ

tasks:
  default:
    desc: Run all checks (test + lint)
    cmds:
      - task: test
      - task: lint

  generate:
    desc: Generate all code (templ templates)
    cmds:
      - task: templ:generate

  templ:generate:
    desc: Generate Go code from templ templates
    cmds:
      - "{{.TEMPL}} generate"

  templ:watch:
    desc: Watch templ files and regenerate on change
    cmds:
      - "{{.TEMPL}} generate --watch"

  templ:fmt:
    desc: Format templ files
    cmds:
      - "{{.TEMPL}} fmt ."

  test:
    desc: Run all tests
    cmds:
      - go test ./... {{.CLI_ARGS}}

  test:verbose:
    desc: Run all tests with verbose output
    cmds:
      - go test -v ./... {{.CLI_ARGS}}

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo "Coverage report written to coverage.html"

  lint:
    desc: Run linter
    cmds:
      - "{{.GOLANGCI_LINT}} run ./..."

  lint:fix:
    desc: Run linter and fix issues where possible
    cmds:
      - "{{.GOLANGCI_LINT}} run --fix ./..."

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  fmt:check:
    desc: Check if code is formatted
    cmds:
      - test -z "$(gofmt -l .)"

  build:
    desc: Build the application
    cmds:
      - task: templ:generate
      - go build ./...

  run:
    desc: Run the server
    deps: [templ:generate]
    cmds:
      - go run ./cmd/server

  dev:
    desc: Run the server with templ watch (requires two terminals or tmux)
    cmds:
      - echo "Run 'task templ:watch' in another terminal, then 'task run'"

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  cli:build:
    desc: Build the CLI tool
    cmds:
      - go build -o bin/cwgame ./cmd/cwgame

  cli:run:
    desc: Run the CLI tool with arguments
    cmds:
      - go run ./cmd/cwgame {{.CLI_ARGS}}

  cli:install:
    desc: Install the CLI tool to $GOPATH/bin
    cmds:
      - go install ./cmd/cwgame

  test:e2e:
    desc: Run end-to-end tests using the CLI
    cmds:
      - go test -v ./e2e/... {{.CLI_ARGS}}

  "simulate:player":
    desc: "Simulate another player in a game (usage: task simulate:player -- <lobby-code> [player-name])"
    deps: [cli:build]
    cmds:
      - ./scripts/simulate-player.sh {{.CLI_ARGS}}

  check:
    desc: Run all CI checks (fmt, lint, test)
    cmds:
      - task: fmt:check
      - task: lint
      - task: test
