// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/mcoot/crosswordgame-go2/internal/web/templates/layout"

type HomeData struct {
	layout.PageData
}

func Home(data HomeData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"home\"><h1>Welcome to Crossword Game</h1><p class=\"lead\">A multiplayer word game where players take turns announcing letters and building words on their own grids.</p>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if data.Player == nil {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<section class=\"home-section\"><h2>Get Started</h2><div class=\"card\"><h3>Play as Guest</h3><p>Start playing immediately without creating an account.</p><form action=\"/auth/guest\" method=\"post\" class=\"form-inline\"><input type=\"text\" name=\"display_name\" placeholder=\"Display Name\" required maxlength=\"20\" class=\"input\"> <button type=\"submit\" class=\"btn btn-primary\">Play as Guest</button></form></div><p class=\"text-muted\">Already have an account? <a href=\"/login\">Login</a> or <a href=\"/register\">Register</a></p></section>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<section class=\"home-section\"><h2>Create or Join a Lobby</h2><div class=\"card-grid\"><div class=\"card\"><h3>Create New Lobby</h3><p>Start a new game lobby and invite others to join.</p><form action=\"/lobby\" method=\"post\" class=\"form-stack\"><div class=\"form-group\"><label for=\"grid_size\">Grid Size</label> <select name=\"grid_size\" id=\"grid_size\" class=\"input\"><option value=\"5\" selected>5x5 (Standard)</option> <option value=\"4\">4x4 (Quick)</option> <option value=\"3\">3x3 (Tiny)</option> <option value=\"2\">2x2 (Mini)</option> <option value=\"6\">6x6 (Extended)</option> <option value=\"7\">7x7 (Challenge)</option></select></div><button type=\"submit\" class=\"btn btn-primary\">Create Lobby</button></form></div><div class=\"card\"><h3>Join Existing Lobby</h3><p>Enter a lobby code to join an existing game.</p><form action=\"/lobby/join\" method=\"post\" class=\"form-stack\"><div class=\"form-group\"><label for=\"code\">Lobby Code</label> <input type=\"text\" name=\"code\" id=\"code\" placeholder=\"ABC123\" required maxlength=\"6\" class=\"input input-uppercase\"></div><button type=\"submit\" class=\"btn btn-secondary\">Join Lobby</button></form></div></div></section>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<section class=\"home-section\"><h2>How to Play</h2><ol class=\"rules-list\"><li>Join or create a lobby with friends</li><li>Players take turns announcing a letter</li><li>Everyone places the announced letter on their own grid</li><li>Once grids are full, words are scored horizontally and vertically</li><li>Longer words score more points - full rows/columns score double!</li></ol></section></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base(data.PageData).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
